net:
  host: 'agency.cwb01.test'

firebase:
  project: "cwb01-dev"

environmentJSON: {
  authenticationConfiguration: {
    firebaseConfiguration: {
      firebase: {
        apiKey: "AIzaSyDzhnv-M6FAIuXNQxTvuYXetdRrjLxvY8E",
        authDomain: "cwb01-dev.firebaseapp.com",
      },
      providerFlow: 'redirect',
      providerId: 'oidc.agency',
      tenantId: 'agency-portal-euxjr',
    },
  },
  httpConfiguration: {
    baseUrl: 'http://api.cwb01.test',
  },
}
